apiVersion: v1
kind: Service
metadata:
  name: whatismypod
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: whatismypod
    origin: ovhplatform
---
apiVersion: v1
kind: Service
metadata:
  name: whatismypod-preview-service
  namespace: default
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: whatismypod
    origin: ovhplatform
